# Generated by Django 5.2.7 on 2025-12-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SearchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "query",
                    models.CharField(
                        help_text="Ключові слова для пошуку",
                        max_length=255,
                        verbose_name="Пошуковий запит",
                    ),
                ),
                (
                    "filters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Застосовані фільтри (ціна, локація, тип і т.д.)",
                        verbose_name="Фільтри",
                    ),
                ),
                (
                    "results_count",
                    models.IntegerField(
                        default=0,
                        help_text="Скільки оголошень знайдено",
                        verbose_name="Кількість результатів",
                    ),
                ),
            ],
            options={
                "verbose_name": "Історія пошуку",
                "verbose_name_plural": "Історія пошуків",
                "ordering": ["-created_at"],
            },
        ),
    ]
