# Generated by Django 5.2.7 on 2025-12-21 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="searchhistory",
            table="search_searchhistory",
        ),
    ]
