# Generated by Django 5.2.7 on 2025-12-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("country", models.CharField(max_length=100, verbose_name="Country")),
                ("city", models.CharField(max_length=100, verbose_name="City")),
                (
                    "address",
                    models.CharField(max_length=255, verbose_name="Street Address"),
                ),
                (
                    "normalized_address",
                    models.CharField(
                        editable=False,
                        max_length=255,
                        verbose_name="Normalized Address",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
            ],
            options={
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
                "ordering": ["city", "country"],
                "indexes": [
                    models.Index(
                        fields=["city", "country"], name="common_loca_city_d50631_idx"
                    ),
                    models.Index(
                        fields=["normalized_address"],
                        name="common_loca_normali_1cc6f0_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("country", "city", "normalized_address"),
                        name="unique_normalized_location",
                    )
                ],
            },
        ),
    ]
