# Generated by Django 5.2.7 on 2025-12-17 08:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Name"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Назва іконки (наприклад: wifi, parking, pool)",
                        max_length=50,
                        verbose_name="Icon",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Amenity",
                "verbose_name_plural": "Amenities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ListingPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "image",
                    models.ImageField(
                        upload_to="listings/%Y/%m/%d/", verbose_name="Image"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Caption"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Порядок відображення фото",
                        verbose_name="Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Listing Photo",
                "verbose_name_plural": "Listing Photos",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "title",
                    models.CharField(
                        help_text="Максимум 255 символів",
                        max_length=255,
                        verbose_name="Title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Максимум 2000 символів",
                        max_length=2000,
                        verbose_name="Description",
                    ),
                ),
                (
                    "is_hotel_apartment",
                    models.BooleanField(
                        default=False,
                        help_text="Квартира готельного типу (здаються окремі кімнати). Якщо True, дозволяється декілька оголошень на одну адресу. Максимум 20 кімнат на адресу.",
                        verbose_name="Hotel-type Apartment",
                    ),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("apartment", "Квартира"),
                            ("studio", "Студія"),
                            ("penthouse", "Пентхаус"),
                            ("loft", "Лофт"),
                            ("duplex", "Дуплекс"),
                            ("house", "Будинок"),
                            ("villa", "Вілла"),
                            ("cottage", "Котедж"),
                            ("townhouse", "Таунхаус"),
                            ("bungalow", "Бунгало"),
                            ("mansion", "Особняк"),
                            ("cabin", "Дача"),
                            ("chalet", "Шале"),
                            ("farmhouse", "Фермерський будинок"),
                            ("country_house", "Заміський будинок"),
                            ("room", "Кімната"),
                            ("shared_room", "Спільна кімната"),
                            ("hostel", "Хостел"),
                            ("castle", "Замок"),
                            ("boat", "Човен/Яхта"),
                            ("houseboat", "Плавучий будинок"),
                            ("camper", "Кемпер/RV"),
                            ("tent", "Намет"),
                            ("treehouse", "Будиночок на дереві"),
                            ("igloo", "Іглу"),
                            ("yurt", "Юрта"),
                            ("lighthouse", "Маяк"),
                            ("other", "Інше"),
                        ],
                        max_length=50,
                        verbose_name="Property Type",
                    ),
                ),
                (
                    "num_rooms",
                    models.PositiveIntegerField(
                        help_text="Від 1 до 20 кімнат. Для hotel apartments - кількість кімнат у цьому оголошенні (що здаються)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                        verbose_name="Number of Rooms",
                    ),
                ),
                (
                    "num_bedrooms",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Від 0 до 20 спалень",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(20),
                        ],
                        verbose_name="Number of Bedrooms",
                    ),
                ),
                (
                    "num_bathrooms",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Від 1 до 10 ванних кімнат",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Number of Bathrooms",
                    ),
                ),
                (
                    "max_guests",
                    models.PositiveIntegerField(
                        help_text="Від 1 до 50 гостей",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(50),
                        ],
                        verbose_name="Maximum Guests",
                    ),
                ),
                (
                    "area",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Від 10 до 10000 кв.м.",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                        verbose_name="Area (sq.m.)",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Від 10 до 1000000 за ніч",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(1000000),
                        ],
                        verbose_name="Price per Night",
                    ),
                ),
                (
                    "cleaning_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Одноразовий прибиральний збір",
                        max_digits=10,
                        null=True,
                        verbose_name="Cleaning Fee",
                    ),
                ),
                (
                    "cancellation_policy",
                    models.CharField(
                        choices=[
                            ("flexible", "Гнучка"),
                            ("moderate", "Помірна"),
                            ("strict", "Жорстка"),
                            ("super_strict", "Дуже жорстка"),
                            ("non_refundable", "Без повернення"),
                        ],
                        default="moderate",
                        max_length=20,
                        verbose_name="Cancellation Policy",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Чи відображається оголошення на сайті",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Чи підтверджено оголошення адміністратором",
                        verbose_name="Is Verified",
                    ),
                ),
                (
                    "amenities",
                    models.ManyToManyField(
                        blank=True,
                        related_name="listings",
                        to="listings.amenity",
                        verbose_name="Amenities",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="listings",
                        to="common.location",
                        verbose_name="Location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Listing",
                "verbose_name_plural": "Listings",
                "ordering": ["-created_at"],
            },
        ),
    ]
