# Generated by Django 5.2.7 on 2025-12-17 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("listings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
        migrations.AddField(
            model_name="listingphoto",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="listings.listing",
                verbose_name="Listing",
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["location"], name="listings_li_locatio_a9bbe4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["owner", "-created_at"], name="listings_li_owner_i_efae9b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["is_active", "is_verified"],
                name="listings_li_is_acti_347014_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(fields=["price"], name="listings_li_price_d6caaa_idx"),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["property_type"], name="listings_li_propert_7a505c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["is_hotel_apartment"], name="listings_li_is_hote_fccdfd_idx"
            ),
        ),
    ]
