# Generated by Django 5.2.7 on 2025-12-17 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListingPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Price per Night"
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_records",
                        to="listings.listing",
                        verbose_name="Listing",
                    ),
                ),
            ],
            options={
                "verbose_name": "Listing Price",
                "verbose_name_plural": "Listing Prices",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("listing", "amount"), name="unique_listing_price_amount"
                    )
                ],
            },
        ),
    ]
