# Generated by Django 5.2.7 on 2025-12-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listingprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingphoto',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Is main photo'),
        ),
    ]
