# Generated by Django 5.2.7 on 2026-01-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listingphoto_is_main'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listingphoto',
            options={'ordering': ['-is_main', 'order', 'created_at'], 'verbose_name': 'Listing Photo', 'verbose_name_plural': 'Listing Photos'},
        ),
        migrations.AddConstraint(
            model_name='listingphoto',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('listing',), name='unique_main_photo_per_listing'),
        ),
    ]
