# Generated by Django 5.2.7 on 2025-12-17 08:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("check_in", models.DateField(verbose_name="Check-in Date")),
                ("check_out", models.DateField(verbose_name="Check-out Date")),
                (
                    "num_guests",
                    models.PositiveIntegerField(
                        help_text="Від 1 до 50 гостей",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(50),
                        ],
                        verbose_name="Number of Guests",
                    ),
                ),
                (
                    "price_per_night",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Ціна на момент бронювання",
                        max_digits=10,
                        verbose_name="Price per Night",
                    ),
                ),
                (
                    "num_nights",
                    models.PositiveIntegerField(
                        help_text="Від 1 до 365 ночей",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(365),
                        ],
                        verbose_name="Number of Nights",
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="price_per_night * num_nights",
                        max_digits=10,
                        verbose_name="Base Price",
                    ),
                ),
                (
                    "cleaning_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Cleaning Fee",
                    ),
                ),
                (
                    "platform_fee",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="10% від загальної суми",
                        max_digits=10,
                        verbose_name="Platform Fee",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Повна вартість бронювання",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Total Price",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Очікує підтвердження"),
                            ("confirmed", "Підтверджено"),
                            ("cancelled", "Скасовано"),
                            ("completed", "Завершено"),
                            ("rejected", "Відхилено"),
                            ("in_progress", "В процесі"),
                            ("expired", "Прострочено"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Booking Status",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Payment Status",
                    ),
                ),
                (
                    "special_requests",
                    models.TextField(
                        blank=True,
                        help_text="Максимум 1000 символів",
                        max_length=1000,
                        verbose_name="Special Requests",
                    ),
                ),
                (
                    "cancellation_policy",
                    models.CharField(
                        choices=[
                            ("flexible", "Гнучка"),
                            ("moderate", "Помірна"),
                            ("strict", "Жорстка"),
                            ("super_strict", "Дуже жорстка"),
                            ("non_refundable", "Без повернення"),
                        ],
                        help_text="Політика скасування на момент бронювання",
                        max_length=20,
                        verbose_name="Cancellation Policy",
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Cancelled At"
                    ),
                ),
                (
                    "cancellation_reason",
                    models.TextField(blank=True, verbose_name="Cancellation Reason"),
                ),
            ],
            options={
                "verbose_name": "Booking",
                "verbose_name_plural": "Bookings",
                "ordering": ["-created_at"],
            },
        ),
    ]
