# Generated by Django 5.2.7 on 2025-12-17 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_initial"),
        ("listings", "0003_listingprice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="price_per_night",
            field=models.ForeignKey(
                help_text="Ціна на момент бронювання",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="listings.listingprice",
                verbose_name="Price per Night",
            ),
        ),
    ]
