# Generated by Django 5.2.7 on 2025-12-17 12:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_alter_booking_price_per_night"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="num_nights",
            field=models.PositiveIntegerField(
                editable=False,
                help_text="Від 1 до 365 ночей",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(365),
                ],
                verbose_name="Number of Nights",
            ),
        ),
    ]
