# Generated by Django 5.2.7 on 2025-12-17 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analytics", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="listingview",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="listingview",
            index=models.Index(
                fields=["listing"], name="analytics_l_listing_7d2271_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listingview",
            index=models.Index(fields=["user"], name="analytics_l_user_id_f94229_idx"),
        ),
    ]
