# Generated by Django 5.2.7 on 2025-12-17 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListingRating",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "listing",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="rating_stats",
                        serialize=False,
                        to="listings.listing",
                        verbose_name="Listing",
                    ),
                ),
                (
                    "average_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Середній рейтинг (0.00 - 5.00)",
                        max_digits=3,
                        verbose_name="Average Rating",
                    ),
                ),
                (
                    "total_reviews",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Загальна кількість відгуків",
                        verbose_name="Total Reviews",
                    ),
                ),
                (
                    "stars_5",
                    models.PositiveIntegerField(default=0, verbose_name="5 Stars"),
                ),
                (
                    "stars_4",
                    models.PositiveIntegerField(default=0, verbose_name="4 Stars"),
                ),
                (
                    "stars_3",
                    models.PositiveIntegerField(default=0, verbose_name="3 Stars"),
                ),
                (
                    "stars_2",
                    models.PositiveIntegerField(default=0, verbose_name="2 Stars"),
                ),
                (
                    "stars_1",
                    models.PositiveIntegerField(default=0, verbose_name="1 Star"),
                ),
            ],
            options={
                "verbose_name": "Listing Rating",
                "verbose_name_plural": "Listing Ratings",
            },
        ),
    ]
