# Generated by Django 5.2.7 on 2025-12-17 08:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0002_initial"),
        ("listings", "0002_initial"),
        ("reviews", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OwnerRating",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="owner_rating_stats",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
                (
                    "average_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Середній рейтинг власника (0.00 - 5.00)",
                        max_digits=3,
                        verbose_name="Average Rating",
                    ),
                ),
                (
                    "total_reviews",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Загальна кількість відгуків на всі оголошення",
                        verbose_name="Total Reviews",
                    ),
                ),
                (
                    "total_listings",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Кількість оголошень з відгуками",
                        verbose_name="Total Listings",
                    ),
                ),
                (
                    "stars_5",
                    models.PositiveIntegerField(default=0, verbose_name="5 Stars"),
                ),
                (
                    "stars_4",
                    models.PositiveIntegerField(default=0, verbose_name="4 Stars"),
                ),
                (
                    "stars_3",
                    models.PositiveIntegerField(default=0, verbose_name="3 Stars"),
                ),
                (
                    "stars_2",
                    models.PositiveIntegerField(default=0, verbose_name="2 Stars"),
                ),
                (
                    "stars_1",
                    models.PositiveIntegerField(default=0, verbose_name="1 Star"),
                ),
            ],
            options={
                "verbose_name": "Owner Rating",
                "verbose_name_plural": "Owner Ratings",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "rating",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Загальний рейтинг від 1 до 5 зірок",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Overall Rating",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Текстовий відгук (мінімум 10, максимум 2000 символів)",
                        max_length=2000,
                        verbose_name="Comment",
                    ),
                ),
                (
                    "owner_response",
                    models.TextField(
                        blank=True,
                        help_text="Відповідь власника (максимум 1000 символів)",
                        max_length=1000,
                        verbose_name="Owner Response",
                    ),
                ),
                (
                    "owner_response_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Owner Response Date"
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True,
                        help_text="Чи відображається відгук на сайті",
                        verbose_name="Is Visible",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=True,
                        help_text="Підтверджений відгук (від реального гостя)",
                        verbose_name="Is Verified",
                    ),
                ),
                (
                    "booking",
                    models.OneToOneField(
                        help_text="Бронювання, за яке залишено відгук",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="bookings.booking",
                        verbose_name="Booking",
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="listings.listing",
                        verbose_name="Listing",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews_written",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reviewer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["listing", "-created_at"],
                        name="reviews_rev_listing_f73afe_idx",
                    ),
                    models.Index(
                        fields=["reviewer", "-created_at"],
                        name="reviews_rev_reviewe_5e332e_idx",
                    ),
                    models.Index(
                        fields=["rating"], name="reviews_rev_rating_2db6dd_idx"
                    ),
                    models.Index(
                        fields=["is_visible", "-created_at"],
                        name="reviews_rev_is_visi_d4dedd_idx",
                    ),
                ],
            },
        ),
    ]
