# Generated by Django 5.2.7 on 2025-12-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                (
                    "message",
                    models.TextField(
                        help_text="Детальний текст сповіщення",
                        verbose_name="Повідомлення",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("BOOKING", "Бронювання"),
                            ("REVIEW", "Відгук"),
                            ("PAYMENT", "Платіж"),
                            ("MESSAGE", "Повідомлення"),
                            ("SYSTEM", "Системне"),
                        ],
                        default="SYSTEM",
                        max_length=50,
                        verbose_name="Тип сповіщення",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False,
                        help_text="Чи переглянув користувач це сповіщення",
                        verbose_name="Прочитано",
                    ),
                ),
                (
                    "related_object_id",
                    models.IntegerField(
                        blank=True,
                        help_text="ID бронювання, відгуку або іншого об'єкта",
                        null=True,
                        verbose_name="ID пов'язаного об'єкта",
                    ),
                ),
                (
                    "related_object_type",
                    models.CharField(
                        blank=True,
                        help_text="booking, review, payment і т.д.",
                        max_length=50,
                        null=True,
                        verbose_name="Тип пов'язаного об'єкта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сповіщення",
                "verbose_name_plural": "Сповіщення",
                "ordering": ["-created_at"],
            },
        ),
    ]
