# Generated by Django 5.2.7 on 2026-01-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('BOOKING', 'Бронювання'), ('REVIEW', 'Відгук'), ('PAYMENT', 'Платіж'), ('MESSAGE', 'Повідомлення'), ('SYSTEM', 'Системне'), ('LISTING', 'Оголошення')], default='SYSTEM', max_length=50, verbose_name='Тип сповіщення'),
        ),
    ]
